### ISSUE TITLE
Sanitize RichTextarea

### ISSUE THREAD

**Issue by Sitetools** [alleyinteractive/wordpress-fieldmanager#615] opened 2017-03-01 20:53 UTC
I've been trying to allow pasting of an iframe into a RichTextarea (a google map) but it keeps on getting stripped out.
I have tried different variations of a solution provieded in a prefious post but can't get it to work, her is an example of what I'm trying to fix. What am I doing wrong?
    //contact page
    if(  isset($_GET['post']) && $_GET['post'] == 11 || $_POST  ){

        $hb = new Fieldmanager_Group( array(
                'name' => 'contact_right_column',
                'limit' => 1,
                'label' => 'Right Column',
                'collapsed' => FALSE,
               ** 'sanitize' => 'wp_kses_post',**
                'children' => array(
                        'copy' => new Fieldmanager_RichTextarea( 'Copy' ),
                ),
        ) );
        $hb->add_meta_box( 'Right Column', array( 'page' ) );
    }

Thank you.

**Comment by dlh01** [comment] 2017-03-02 06:08
Hi @Sitetools,

- As far as I know, neither `wp_filter_post_kses()` (the default sanitizer for `RichTextAreas`) nor `wp_kses_post()` allow `<iframe>` elements. You'll need to use a sanitizing function that allows those. You might also have a look at how the `content_save_pre` filter handles sanitizing post content.

- Note also that the `sanitize` property should be passed to your `Fieldmanager_RichTextArea`, not the `Fieldmanager_Group`.

- Depending on the users you are trying to let paste `<iframe>`s, this could be considered a duplicate of #231.

**Comment by Sitetools** [comment] 2017-03-02 20:21
Thanks for your reply, I found a solution to allow iframes here:
https://gist.github.com/bjorn2404/8afe35383a29d2dd1135ae0a39dc018c

**Closed** 2017-03-02 21:43 UTC
