### ISSUE TITLE
Previewing changes to Fieldmanager fields

### ISSUE THREAD

**Issue by vigilanteweb** [alleyinteractive/wordpress-fieldmanager#302] opened 2015-01-30 19:12 UTC
I am not able to preview the changes I make to my Fieldmanager fields even when the WordPress autosave fires. Is there a way to hook into the autosave routine to save Fieldmanager fields as well?

**Comment by mboynes** [comment] 2016-02-20 00:04
This is a tough nut to crack. I'm closing this as "won't fix" for now, because I don't see this making it into FM core. I did start an add-on plugin for this: https://github.com/alleyinteractive/fieldmanager-revisions-alpha

**Closed by mboynes** 2016-02-20 00:04 UTC
Labels: revisions

**Comment by nicoladj77** [comment] 2024-01-21 14:26
@mboynes did you ever find a solution to this?

**Comment by mboynes** [comment] 2024-01-21 17:20
@nicoladj77 I used https://github.com/alleyinteractive/fieldmanager-revisions-alpha on several production projects and it fit our needs. Despite using it on production, I maintained its "alpha" status because WordPress core was working toward adding native support for revisioning post meta. Great news for you: [this was recently (finally!) included in WordPress 6.4](https://make.wordpress.org/core/2023/10/24/framework-for-storing-revisions-of-post-meta-in-6-4/). I haven't used it yet, so I can't tell you if previews work out-of-the-box or not, but the release notes suggest that they should. If they don't, I expect the lift to make that work would be pretty minimal, and you'd find prior art in my aforementioned [revisions plugin](https://github.com/alleyinteractive/fieldmanager-revisions-alpha).

**Comment by nicoladj77** [comment] 2024-01-22 22:09
@mboynes ok thanks. It doesn't work out of the box but I will try to get it working with 6.4 changes.

**Comment by nicoladj77** [comment] 2024-03-11 06:31
@mboynes so I am currently trying to get this to work with post meta revisions.
What I did is this:
added a simple metabox:

		$fm = new \Fieldmanager_TextField( 'panelists', [ 'name' => 'testing' ] );
		$fm->add_meta_box( 'Panellists', $this->get_post_types(), 'normal' );

and enabled revisions for that field

		register_meta(
			'post',
			'testing',
			[
				'show_in_rest'      => true,
				'single'            => true,
				'type'              => 'string',
				'revisions_enabled' => true,
			]
		); 

The problem is that the content of the metabox is not sent in the autosave object ( I see that the meta key 'testing' is set, but it's an empty screen even if I enter something in the metabox), and thus it ends up empty in the revision. 
Is there something that I am missing?
