### ISSUE TITLE
Fieldmanager nested groups only sortable when Add More button is present

### ISSUE THREAD

**Issue by akaufman3** [alleyinteractive/wordpress-fieldmanager#683] opened 2018-01-04 18:23 UTC
Trying to create an set number of groups nested in a larger group. Want to have the ability to sort the nested groups. This only works when Add More is present. 
<img width="730" alt="screen shot 2018-01-04 at 1 22 42 pm" src="https://user-images.githubusercontent.com/4086943/34578306-6cc06d24-f152-11e7-8b87-26f1353b791a.png">

**Comment by dlh01** [comment] 2018-01-05 04:05
Hi @akaufman3,

To confirm, in the screenshot, you would want to be able to sort `Headline`, `Dek`, `Date`, `Byline`, and `Social Media Icons`? If so, what would be the goal of allowing those fields to be sortable?

**Comment by mboynes** [comment] 2018-01-05 16:03
Possibly a duplicate of #484

**Comment by akaufman3** [comment] 2018-01-05 18:55
@dlh01 Correct. They are a discrete set of options and the user does not have the ability to add more. The goal would be that the output would preserve the order in which they were arranged so that the front end will know which order to render the items.

**Comment by dlh01** [comment] 2018-01-06 13:47
Thanks @akaufman3. Do you think it would be fair to call this an enhancement covered by #484?

**Comment by akaufman3** [comment] 2018-01-08 16:43
Yep @dlh01 thanks.

**Closed** 2018-01-08 16:59 UTC
Labels: duplicate, enhancement

**Comment by theMikeD** [comment] 2022-10-03 18:53
I am now hitting this same request: a fixed number of groups (known at run time) that I would like to use to set the front end order of what they contain. By way of an analogy, similar to (all else being equal) how the menu builder works in stock WP: drag and drop to set the menu order; I'm after the same idea here. 

If I read the above here correctly, this is not possible. And since the suggested related ticket is six years old, I'm guessing it's not going to be...unless there is a work-around I haven't figured out yet?
