### ISSUE TITLE
VIP Go unable to save field values

### ISSUE THREAD

**Issue by ConnectedCat** [alleyinteractive/wordpress-fieldmanager#518] opened 2016-08-12 01:11 UTC
Using the basic example from the documentation:

```
add_action( 'fm_post_post', function() {
  $fm = new Fieldmanager_Group( array(
    'name' => 'contact_information',
    'children' => array(
      'name' => new Fieldmanager_Textfield( 'Name' ),
      'phone' => new Fieldmanager_Textfield( 'Phone Number' ),
      'website' => new Fieldmanager_Link( 'Website' ),
    ),
  ) );
  $fm->add_meta_box( 'Contact Information', 'post' );
} );
```

inside the inc/customizer.php in the [_s theme](https://github.com/automattic/_s) I am able to render the field group on the page but unable to save any information in those fields. Standard WP fields save without issue.
The instance is running on a freshly provisioned Vagrant box as per VIP Go [instructions](https://github.com/Automattic/vip-go-quickstart)
Please let me know if I can provide any other details
Thank you

**Comment by bcampeau** [comment] 2016-08-12 11:12
There's nothing wrong with your code and I've tested that exact snippet on a vanilla WP install and it works just fine. 

There must be something else in your theme or another plugin causing a conflict. Unfortunately that's out of scope for us to help you troubleshoot. We'd recommend using a tool like Xdebug to step through the saving process and see where the issue lies.

If you find any additional information that points at the plugin, please let us know and we can reopen this issue and help you troubleshoot further.

**Closed by bcampeau** 2016-08-12 11:12 UTC
Labels: question

**Comment by mslinnea** [comment] 2016-08-22 02:05
@ConnectedCat, I also had this problem recently, and have found that there is an issue with the plugin WP Cron Control, packed with the VIP MU plugins.  Try deleting `wp-cron-control.php` and the `wp-cron-control` directory.  The issue is that plugin sets `DOING_CRON` to true, which causes Fieldmanager to run the wrong functions, which ends up in the fields not saving.

**Comment by hellodev-maxim** [comment] 2016-09-02 16:04
I removed the _wp-cron-control_ for now and got things working, thanks

**Comment by emrikol** [comment] 2016-09-30 18:12
For future reference, the wp-cron-control issue on VIP Go [has been fixed](https://github.com/Automattic/WP-Cron-Control/commit/fcf17400479dbb25e7be41902cd0425b9b881b11).
