### ISSUE TITLE
Safari repeatable richtext bug

### ISSUE THREAD

**Issue by nschoenholtz** [alleyinteractive/wordpress-fieldmanager#372] opened 2015-08-13 17:14 UTC
In Safari (currently 8.0.7 on OSX 10.10.4 but also reproduced in OSX 10.9), reordering new repeatable richtext fields results in a bug and lost data.

Steps:
- Using https://github.com/alleyinteractive/fieldmanager-demos RichTextAreas example, create new post (or use an existing post if you have one)
- In the **Repeatable RichTextAreas** section, ignore the preexisting field and instead _Add another field_
- Type something into the new field
- Drag the new field above the preexisting field
- You'll see the content disappear and the TinyMCE instance becomes non-responsive. You'll also see an error in the JS console, `TypeError: undefined is not an object (evaluating 'a.createRange')`

**Comment by mboynes** [comment] 2016-02-20 01:08
This seems worse than described. I was able to drag any RTA and it broke. I don't have any immediate answers for this one, could use some assistance from a JS dev.

**Comment by dlh01** [comment] 2016-12-27 04:23
I might be doing something wrong, but I'm unable to replicate this behavior as described with Safari 10.0.1 on macOS 10.12.1.

**Comment by mboynes** [comment] 2017-10-12 18:32
This bug is still alive and well in Safari 11.0 on macOS 10.12.6.

**Comment by dlh01** [comment] 2021-02-16 06:43
Closing as a duplicate of #502, even though this is older, as it has some example code that can be used for testing.

**Closed by dlh01** 2021-02-16 06:43 UTC
Labels: bug, help wanted
