### ISSUE TITLE
Fieldmanager_RichTextArea Tinymce not initialising

### ISSUE THREAD

**Issue by pressoholics** [alleyinteractive/wordpress-fieldmanager#720] opened 2018-08-03 15:39 UTC
We have some Rich Text Area fields in field groups which are show/hidden using display_if. 

https://cl.ly/3z370h3b3B0B

These fields fail to initialize Tinymce. Sometimes you can get it initialize by either:

* blindly pasting content into the empty field and saving the post
* Clicking the text/visual tabs a few times
* changing a drop down field value within the same group
* sometime just refreshing the page also helps 

Have you come across this issue before, I can't see any console JS errors or PHP errors in the PW debug log file.

We are using version 1.2.3 of the plugin on the WordPress VIP platform.

Thanks in advance

**Comment by sudar** [comment] 2020-02-13 13:35
We are facing this issue as well.

Is there any workaround for this till the issue is fixed in Field manager?

**Comment by kevinfodness** [comment] 2020-04-15 16:38
Fixed via #757

**Closed by kevinfodness** 2020-04-15 16:38 UTC
